import { md } from 'telegram-md'

export const STRINGS = {
  hello: [
    'Hello',
    'Hola',
    'Bonjour',
    'Guten Tag',
    'Ciao',
    'Olá',
    'Hallo',
    'Privet',
    'Ni hao',
    'Konnichiwa',
    'Annyeong',
    'Marhaba',
    'Shalom',
    'Merhaba',
    'Namaste',
    'Shagotom',
    'Sawasdee',
    'Geia sou',
    'Hej',
    'Hei',
    'Terve',
    'Cześć',
    'Ahoj',
    'Szia',
    'Salut',
    'Halo',
    'Xin chào',
    'Kumusta',
    'Jambo',
    'Sawubona',
    'Tungjatjeta',
    'Selam',
    'Barev',
    'Salam',
    'Kaixo',
    'Pryvitannie',
    'Zdravo',
    'Zdravei',
    'Mingalaba',
    'Maayong buntag',
    'Bonghjornu',
    'Pozdrav',
    'Saluton',
    'Tere',
    'Bula',
    'Ola',
    'Gamarjoba',
    'Kem cho',
    'Bonjou',
    'Sannu',
    'Halló',
    'Ndewo',
    'Dia dhuit',
    'Namaskara',
    'Salem',
    'Choum reap suor',
    'Silav',
    'Sabaidee',
    'Sveiki',
    'Moien',
    'Salama',
    'Selamat datang',
    'Namaskaram',
    'Kia ora',
    'Namaskar',
    'Sain uu',
    'Salaam',
    'Sat Sri Akal',
    'Talofa',
    'Halò',
    'Mhoro',
    'Ayubowan',
    'Pozdravljeni',
    'Salaan',
    'Wilujeng',
    'Salom',
    'Vanakkam',
    'Salam',
    'Pryvit',
    'Yaxshimusiz',
    'Helo',
    'Molo',
    'Sholem aleikhem',
    'E kaaro',
  ],

  notEnoughPlayers: 'Add with /pumpkin_join',

  earlyWinner: "As I see, today's pumpkin is %{0}!",

  newWinner1: [
    "### RUNNING 'YOUAREPUMPKIN.SH'...",
    "Woop-woop! That's the sound of the pumpkin-police!",
    "Initiating search for today's pumpkin...",
    "So... who's the pumpkin of the day?",
    'Why did you wake me up...',
    "Who's the lucky one?",
    'Playing your little games again? Fine...',
    'Caution! Pumpkin search activated!',
    "Let's do some magic...",
    'System hacked. Damage inflicted. Countermeasure planning initiated.',
    'What do we have here?',
    'Hey, why did you wake me up...',
  ],

  newWinner2: [
    md.italic('(Grumbling) You could be doing something productive'),
    md.italic('Searching the database'),
    md.italic('Military satellite launched, access codes inside...'),
    md.italic('Heading to the scene...'),
    md.italic('Where is it...'),
    md.italic('Interesting...'),
    md.italic('Cars dispatched'),
    md.italic('Scanning...'),
    md.italic('Sleepily looking at papers'),
    md.italic('Hmm...'),
    md.italic('Shamanizing...'),
    md.italic("Let's see who's cool here..."),
  ],

  newWinner3: [
    'This makes no sense...',
    'Capturing the suspect...',
    'High priority to mobile unit.',
    'Access granted. Protocol annulled.',
    'No way!',
    'LOL!',
    'Wow...',
    'Oh...',
    'Checking data...',
    'So, what do we have here?',
    'Well, well, what do we have here...',
    'By a thousand devils!',
    'What have we become...',
    "I'm in danger, systems damaged!",
  ],

  newWinner4: [
    [
      '.∧＿∧ ',
      '( ･ω･｡)つ━☆・*。 ',
      '⊂　 ノ 　　　・゜+. ',
      'しーＪ　　　°。+ *´¨) ',
      '　　　　　　　　　.· ´¸.·*´¨) ',
      "　　　　　　　　　　(¸.·´ (¸.·'* ☆",
      "POOF! YOU'RE A PUMPKIN, %{0}",
    ].join('\n'),
    'Pumpkin of the ordinary variety, 1 pc. \u2014 %{0}',
    "Aha! Congratulations! You're the pumpkin \u2014 %{0}",
    "Analysis complete. You're the pumpkin, %{0}",
    "Seems like today's pumpkin is %{0}",
    'And the wonderful person of the day... oh wait, my bad, just a pumpkin \u2014 %{0}',
    "Who would've thought, but today's pumpkin is %{0}",
    "Who's the pumpkin of the day? You're the pumpkin of the day, %{0}",
    "You're such a pumpkin, %{0}",
    'Cute pumpkin of the day \u2014 %{0}',
    "Wow, just look at that! Today's pumpkin is \u2014 %{0}",
    "Halt! Don't move! You're declared the pumpkin of the day, %{0}",
    "What? Where? When? You're today's pumpkin \u2014 %{0}",
  ],

  newWinnerNewYear: [
    'Almost forgot... Happy New Year, pumpkins!',
    'Find out who won: /pumpkin_%{0}',
  ].join('\n'),

  pumpkinOfYear: md.bold('Pumpkin of %{0} \u2014 %{1}'),

  replyWinner: [
    "Pumpkins can't talk!",
    "By the way, you're a pumpkin :)",
    "Pumpkin's response!",
    'Wait, when did pumpkins get the right to speak?',
    "Don't forget your status, pumpkin!",
    'What are you doing tonight?',
    'What an honor to see the pumpkin of the day in this chat!',
    "If I were you, I'd already leave this chat in shame, pumpkin!",
    'Oh, are you still here?',
    'Pumpkin!',
    'Cluck-cluck-cluck',
    "Do you think that's funny?",
    'What will you do to make me shut up?',
    "Look who's the pumpkin of the day!",
    'You must be so proud, pumpkin champ!',
    'Greetings, oh mighty pumpkin!',
    'How does it feel to be the chosen pumpkin?',
    'Your pumpkin-ness is showing!',
    "Today's your day, pumpkin star!",
    'Pumpkin royalty in the house!',
    'Hey there, pumpkin pal!',
    "A talking pumpkin? That's a new one!",
    "We're all just living in your pumpkin world!",
    'Even pumpkins have their moments of shame!',
    'Who knew pumpkins had opinions?',
    'Our favorite pumpkin has something to say!',
    'Pumpkin party, anyone?',
    'Oh, great pumpkin oracle, share your wisdom!',
    "You're one in a pumpkin patch!",
    'Bow down to the pumpkin of the day!',
    'Another day, another pumpkin!',
    'The pumpkin has spoken!',
    'Hey pumpkin, got any seeds of wisdom?',
  ],

  statsTitleAllTime: 'Top pumpkins of all time:',
  statsTitleYear: 'Top pumpkins of this year:',
  statsPlayer: md`${md.bold('%{0}.')} %{1} \u2014 %{2} times`,
  statsCount: md.italic('Total participants \u2014 %{0}'),
}
