import { md } from '@vlad-yakovlev/telegram-md'

export const STRINGS = {
  hello: [
    'Ahoj',
    'Annyeong',
    'Ayubowan',
    'Barev',
    'Bonghjornu',
    'Bonjou',
    'Bonjour',
    'Bula',
    'Choum reap suor',
    'Ciao',
    'Cześć',
    'Dia dhuit',
    'E kaaro',
    'Gamarjoba',
    'Geia sou',
    'Guten Tag',
    'Hallo',
    'Halló',
    'Halo',
    'Halò',
    'Hei',
    'Hej',
    'Hello',
    'Helo',
    'Hola',
    'Jambo',
    'Kaixo',
    'Kem cho',
    'Kia ora',
    'Konnichiwa',
    'Kumusta',
    'Maayong buntag',
    'Marhaba',
    'Merhaba',
    'Mhoro',
    'Mingalaba',
    'Moien',
    'Molo',
    'Namaskar',
    'Namaskara',
    'Namaskaram',
    'Namaste',
    'Ndewo',
    'Ni hao',
    'Ola',
    'Olá',
    'Pozdrav',
    'Pozdravljeni',
    'Privet',
    'Pryvit',
    'Pryvitannie',
    'Sabaidee',
    'Sain uu',
    'Salaam',
    'Salaan',
    'Salam',
    'Salam',
    'Salama',
    'Salem',
    'Salom',
    'Salut',
    'Saluton',
    'Sannu',
    'Sat Sri Akal',
    'Sawasdee',
    'Sawubona',
    'Selam',
    'Selamat datang',
    'Shagotom',
    'Shalom',
    'Sholem aleikhem',
    'Silav',
    'Sveiki',
    'Szia',
    'Talofa',
    'Tere',
    'Terve',
    'Tungjatjeta',
    'Vanakkam',
    'Wilujeng',
    'Xin chào',
    'Yaxshimusiz',
    'Zdravei',
    'Zdravo',
  ],

  notEnoughPlayers: ['Add with /pumpkin_join'],

  earlyWinner: ["As I see, today's pumpkin is %{0}!"],

  newWinner1: [
    "### RUNNING 'PUMPKINPATROL.SH'...",
    "### RUNNING 'YOUAREPUMPKIN.SH'...",
    'Analyzing potential pumpkins...',
    "And today's pumpkin is...",
    'Caution! Pumpkin search activated!',
    'Did someone say... pumpkin?',
    'Hey, why did you wake me up...',
    "Hold on to your stems! It's pumpkin time!",
    'Initializing daily pumpkin search...',
    "Initiating search for today's pumpkin...",
    'Is it pumpkin time again?',
    "Let's do some magic...",
    'Playing your little games again? Fine...',
    'Prepare for pumpkin greatness...',
    'Pumpkin seeker activated!',
    "So... who's the pumpkin of the day?",
    'System hacked. Damage inflicted. Countermeasure planning initiated.',
    "Ugh, fine, let's find the pumpkin...",
    'What do we have here?',
    "Who shall be crowned today's pumpkin?",
    "Who's the lucky one?",
    'Why did you wake me up...',
    'Why must you make me do this...',
    "Woop-woop! That's the sound of the pumpkin-police!",
  ],

  newWinner2: [
    md.italic('(Grumbling) You could be doing something productive'),
    md.italic('Aha!'),
    md.italic('Browsing through pumpkin candidates'),
    md.italic('Cars dispatched'),
    md.italic('Deploying pumpkin drones...'),
    md.italic('Fascinating...'),
    md.italic('Fine, I guess I will do the search...'),
    md.italic('Heading to the scene...'),
    md.italic('Hmm...'),
    md.italic('Interesting...'),
    md.italic("Let's see who's cool here..."),
    md.italic('Military satellite launched, access codes inside...'),
    md.italic('Processing...'),
    md.italic('Pumpkinizing...'),
    md.italic('Scanning...'),
    md.italic("Searching for today's pumpkin star..."),
    md.italic('Searching the database'),
    md.italic('Sending out pumpkin scouts'),
    md.italic('Shamanizing...'),
    md.italic('Sigh... here we go again'),
    md.italic('Sleepily looking at papers'),
    md.italic('Traveling through pumpkin dimensions...'),
    md.italic('Where could it be...'),
    md.italic('Where is it...'),
  ],

  newWinner3: [
    'Access granted. Protocol annulled.',
    'Alert: Pumpkin located.',
    'By a thousand devils!',
    'Capturing the suspect...',
    'Checking data...',
    'For the love of pumpkins!',
    'Haha!',
    'High priority to mobile unit.',
    'Hmm...',
    "I can't believe this...",
    "I'm in danger, systems damaged!",
    'Impressive...',
    'LOL!',
    'No way!',
    'Oh...',
    'Securing the pumpkin...',
    'So, what do we have here?',
    'So, who is it this time?',
    'System compromised, pumpkin located!',
    'System override. Pumpkin located.',
    'This is getting out of hand...',
    'This makes no sense...',
    'Unbelievable!',
    'Verifying pumpkin identity...',
    'Well, well, well...',
    'Well, well, what do we have here...',
    'What have we become...',
    'Wow...',
  ],

  newWinner4: [
    [
      '.∧＿∧ ',
      '( ･ω･｡)つ━☆・*。 ',
      '⊂　 ノ 　　　・゜+. ',
      'しーＪ　　　°。+ *´¨) ',
      '　　　　　　　　　.· ´¸.·*´¨) ',
      "　　　　　　　　　　(¸.·´ (¸.·'* ☆",
      "POOF! YOU'RE A PUMPKIN, %{0}",
    ].join('\n'),
    [
      '⊂(・▽・⊂) ',
      '━━━━☆・*。 ',
      '⊃　　　・゜+. ',
      '　＾ω＾　　　°。+ *´¨) ',
      '　　　　　　　.· ´¸.·´¨) ',
      "　　　　　　　　(¸.·´ (¸.·' ☆",
      "SURPRISE! YOU'RE A PUMPKIN, %{0}",
    ].join('\n'),
    "Aha! Congratulations! You're the pumpkin — %{0}",
    "Analysis complete. You're the pumpkin, %{0}",
    'And the esteemed pumpkin of the day goes to... %{0}',
    'And the wonderful person of the day... oh wait, my bad, just a pumpkin — %{0}',
    "Behold! Today's prized pumpkin is — %{0}",
    'Cute pumpkin of the day — %{0}',
    'Feeling pumpkiny today? You should, %{0}',
    "Guess what? You're today's pumpkin star — %{0}",
    "Halt! Don't move! You're declared the pumpkin of the day, %{0}",
    "It's official! Today's pumpkin is %{0}",
    "It's your lucky day, pumpkin! You're it, %{0}",
    'Ordinary pumpkin, but still special — %{0}',
    "Pumpkin analysis complete. You're it, %{0}",
    "Pumpkin of the day, it's you! Congrats, %{0}",
    'Pumpkin of the ordinary variety, 1 pc. — %{0}',
    "Seems like today's pumpkin is %{0}",
    "Stop right there! You've been crowned the pumpkin of the day, %{0}",
    "Surprise! You're today's pumpkin — %{0}",
    'The adorable pumpkin of the day — %{0}',
    "Today's pumpkin royalty is none other than %{0}",
    "What? Where? When? You're today's pumpkin — %{0}",
    "Who would've thought, but today's pumpkin is %{0}",
    "Who's the pumpkin of the day? You're the pumpkin of the day, %{0}",
    "Wow, just look at that! Today's pumpkin is — %{0}",
    "You're such a pumpkin, %{0}",
  ],

  newWinnerNewYear: [
    [
      'Almost forgot... Happy New Year, pumpkins!',
      'Find out who won: /pumpkin_%{0}',
    ].join('\n'),
  ],

  pumpkinOfYear: [md.bold('Pumpkin of %{0} \u2014 %{1}')],

  replyForWinner: [
    "A talking pumpkin? That's a new one!",
    'Another day, another pumpkin!',
    'Bow down to the pumpkin of the day!',
    "By the way, you're a pumpkin :)",
    'Cluck-cluck-cluck',
    "Do you think that's funny?",
    "Don't forget your status, pumpkin!",
    'Even pumpkins have their moments of shame!',
    'Greetings, oh mighty pumpkin!',
    'Hey pumpkin, got any seeds of wisdom?',
    'Hey there, pumpkin pal!',
    'How does it feel to be the chosen pumpkin?',
    "If I were you, I'd already leave this chat in shame, pumpkin!",
    "Look who's the pumpkin of the day!",
    'Oh, are you still here?',
    'Oh, great pumpkin oracle, share your wisdom!',
    'Our favorite pumpkin has something to say!',
    'Pumpkin party, anyone?',
    'Pumpkin royalty in the house!',
    'Pumpkin!',
    "Pumpkin's response!",
    "Pumpkins can't talk!",
    'The pumpkin has spoken!',
    "Today's your day, pumpkin star!",
    'Wait, when did pumpkins get the right to speak?',
    "We're all just living in your pumpkin world!",
    'What an honor to see the pumpkin of the day in this chat!',
    'What are you doing tonight?',
    'What will you do to make me shut up?',
    'Who knew pumpkins had opinions?',
    'You must be so proud, pumpkin champ!',
    "You're one in a pumpkin patch!",
    'Your pumpkin-ness is showing!',
  ],

  statsTitleAllTime: ['Top pumpkins of all time:'],
  statsTitleYear: ['Top pumpkins of this year:'],
  statsPlayer: [md`${md.bold('%{0}.')} %{1} \u2014 %{2} times`],
  statsTotalPlayers: [md.italic('Total participants \u2014 %{0}')],
}
